{{- if .Values.volumes }}
{{- range .Values.volumes }}
{{- if (not .useExistingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "copyparty-helm.labels" . | nindent 4 }}
  name: {{ .name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes: ReadWriteOnce
  {{- end }}
  {{- with .storageClass }}
    {{- if (eq "-" .) }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ . | quote }}
    {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}
{{- end }}